# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=25)),
                ('author_email_id', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('blog', models.URLField()),
                ('total_books_sold', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('author_id',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('ratings', models.CharField(choices=[('1', 'DIRT'), ('2', 'MILD'), ('3', 'MODERATE'), ('4', 'HIGH')], max_length=1)),
                ('no_of_copies_sold_till_date', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineBookStore.Author')),
            ],
            options={
                'ordering': ('ratings',),
            },
        ),
    ]
